enum StoreMutationKeys {
  'ADD_STORE' = 'ADD_STORE',
  'UPDATE_STORE' = 'UPDATE_STORE'
}

enum StoreQueryKeys {
  'GET_LIST_STORES_BY_COMPANY' = 'GET_LIST_STORES_BY_COMPANY',
  'GET_STORE' = 'GET_STORE',
  'AVAILABLE_DOMAIN' = 'AVAILABLE_DOMAIN',
  'GET_STORE_STEUP_BY_STORE_ID' = 'GET_STORE_STEUP_BY_STORE_ID',
  'UPDATE_STORE_SETUP' = 'UPDATE_STORE_SETUP'
}

export { StoreMutationKeys, StoreQueryKeys };
