enum ProductQueryKeys {
  GET_PRODUCT_LIST = 'GET_PRODUCT_LIST',
  GET_PRODUCT_MANAGER_LIST = 'GET_PRODUCT_MANAGER_LIST'
}

enum ProductMutationKeys {
  ADD_PRODUCT_MANAGER = 'ADD_PRODUCT_MANAGER',
  REMOVE_PRODUCT_MANAGER = 'REMOVE_PRODUCT_MANAGER'
}

export { ProductMutationKeys, ProductQueryKeys };
