enum ProductQueryKeys {
  GET_PRODUCT_LIST = 'GET_PRODUCT_LIST',
  GET_PRODUCT_MANAGER_LIST = 'GET_PRODUCT_MANAGER_LIST',
  GET_PRODUCT_MANAGER_LIST_BY_COMPANY = 'GET_PRODUCT_MANAGER_LIST_BY_COMPANY',
  GET_PRODUCT_CLIENT = 'GET_PRODUCT_CLIENT'
}

enum ProductMutationKeys {
  ADD_PRODUCT_MANAGER = 'ADD_PRODUCT_MANAGER',
  ADD_PRODUCT_IMAGES = 'ADD_PRODUCT_IMAGES',
  REMOVE_PRODUCT_MANAGER = 'REMOVE_PRODUCT_MANAGER'
}

export { ProductMutationKeys, ProductQueryKeys };
